baseURL = 'http://burtchell.dev'
languageCode = 'en-us'
title = 'burtchell'

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "cv"
    url = "/cv"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "teaching"
    url = "/teaching"
    weight = 15
  
  [[menu.main]]
    identifier = "links"
    name = "links"
    url = "/links"
    weight = 20
  
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 30

  [[menu.external]]
    identifier = "Github"
    pre = "github"
    url = "https://github.com/dukeofjukes"
    weight = 10

  [[menu.external]]
    identifier = "Linkedin"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/brandon-burtchell/"
    weight = 20

